project_id = "kkbgxovmdpdjnblliqka"

[functions.generate-certificate]
verify_jwt = true

[functions.send-certificate]
verify_jwt = true

[functions.get-test-questions]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
