project_id = "kkbgxovmdpdjnblliqka"

[functions.generate-certificate]
verify_jwt = true

[functions.send-certificate]
verify_jwt = true

[functions.create-admin]
verify_jwt = false

[functions.get-test-questions]
verify_jwt = false